export enum ApiPaths {
  Auth = '/auth',
  AuthLogin = '/auth/login',
  Folder = '/folders',
  FolderTree = '/folders/tree',
  Document = '/documents',
  DocumentUpload = '/documents/upload',
  DocumentDownload = '/documents/download',
  DocColPref = "/preferences/document-columns",
  DocumentType = "/types",
  User = "/users",
  UserDetails = "/users/details",
  Administration = "/administration",
  AdministrationDocument = "/administration/documents",
  AdministrationFolder = "/administration/folders",
  AdministrationGrant = "/administration/grant",
}
